import {Repository } from "../components/ListRepositories";

export const lista: Repository[] = [
  {
    id: "1",
    name: "app_busca_github_desafio",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "2",
    name: "cursos-reactjs-school-of-net",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "3",
    name: "be-the-hero",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "4",
    name: "ignite-lab-rockethelp",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: true,
  },
  {
    id: "5",
    name: "rockethelp",
    language: "Java",
    languageList: ["Java"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "6",
    name: "app_typescript_teste",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "7",
    name: "cardapio_app_v2",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "8",
    name: "app_dart_teste",
    language: "Dart",
    languageList: ["Dart"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "9",
    name: "typescript_curso",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "10",
    name: "carrinho_compras",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "11",
    name: "cursos-nodejs-school-of-net",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "12",
    name: "carrinho_compras_api",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "13",
    name: "gera_uuid",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "14",
    name: "wordpress_teste",
    language: "PHP",
    languageList: ["PHP"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "15",
    name: "email_marketing_htarketing_html_css",
    language: "HTML",
    languageList: ["HTML"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "16",
    name: "cursos-react-native-school-of-net",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "17",
    name: "cursos-reactnative-school-of-net",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "18",
    name: "",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "19",
    name: "cardapio_app_server",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "20",
    name: "teste_auth",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "21",
    name: "cardapio_app_web",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "22",
    name: "cardapio_app_dashboard",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "23",
    name: "cardapio_app_dashboard_empresa",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "24",
    name: "leitor_codigo_barras",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "25",
    name: "react_upload_image_server",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "26",
    name: "react_upload_image_frontend",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "27",
    name: "cursos-graphql-school-of-net",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "28",
    name: "challenge_d3_covid19_monitor",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "29",
    name: "frontend_vaga_mypharma",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "30",
    name: "backend_vaga_mypharma",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "31",
    name: "cardapio-app-backend",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "32",
    name: "d3_challenge_covid19_monitor",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "33",
    name: "jest_teste",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "34",
    name: "curso-typescript-alura",
    language: "JavaScript ",
    languageList: ["JavaScript "],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "35",
    name: "chat_app",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "36",
    name: "chat_app_server",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "37",
    name: "aluracord",
    language: "JavaScript ",
    languageList: ["JavaScript "],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "38",
    name: "aluracord-matrix",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: true,
  },
  {
    id: "39",
    name: "enciclopedia_veiculos_app",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "40",
    name: "enciclopedia_veiculos_app_server",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "41",
    name: "calcula_medida_app",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "42",
    name: "calculadora_medidas_app",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "43",
    name: "fale_mais_app",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "44",
    name: "alurakut",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "45",
    name: "iam_software",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "46",
    name: "iam_software_react",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "47",
    name: "trabalho-iam-software-backup",
    language: "PHP",
    languageList: ["PHP"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "48",
    name: "enciclopedia-veiculos-app-server",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "49",
    name: "enciclopedia-veiculos-app",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "50",
    name: "iam-software",
    language: "PHP",
    languageList: ["PHP"],
    license: "",
    archived: false,
    private: true,
    fork: true,
  },
  {
    id: "51",
    name: "enciclopedia-veiculos-app-backend",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "52",
    name: "iam-software-detalhes",
    language: "Vue",
    languageList: ["Vue"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "53",
    name: "lista-tarefas-app-v2",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "54",
    name: "lista-tarefas-app",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "55",
    name: "curso-node-js-alura",
    language: "CSS",
    languageList: ["CSS"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "56",
    name: "app_calcula_medida",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "57",
    name: "api_teste_nodejs",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "58",
    name: "teste_react",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "59",
    name: "app-loja-game-reactjs",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "60",
    name: "app-loja-game-reactjs-backend",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "61",
    name: "marvel_app",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "62",
    name: "carrinho-de-compras",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "63",
    name: "app-bolsa-valores-react-native",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "64",
    name: "app-reactjs-bolsa-valores",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "65",
    name: "teste-reactjs",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "66",
    name: "app-bolsa-valores-reactjs",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "67",
    name: "reactjs-redux-app",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "68",
    name: "e-commerce-game-app",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "69",
    name: "e-commerce-app",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "70",
    name: "nlw06",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "71",
    name: "nlw05",
    language: "Dart",
    languageList: ["Dart"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "72",
    name: "marvel_app_api",
    language: "TypeScript ",
    languageList: ["TypeScript "],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "73",
    name: "marvel_app_api_server_test",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "74",
    name: "e-commerce-app-2",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "75",
    name: "app_calculadora",
    language: "Dart",
    languageList: ["Dart"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "76",
    name: "lista_produtos_v2",
    language: "Dart",
    languageList: ["Dart"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "77",
    name: "nlw05-1",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "78",
    name: "app_calculadora_1",
    language: "Dart",
    languageList: ["Dart"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "79",
    name: "app-calculadora-js",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "80",
    name: "app-vecx-system-v1",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "81",
    name: "teste_chat_app_frontend",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "82",
    name: "imersao_dev_alura",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "83",
    name: "curso_javascript_cod3r",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "84",
    name: "lista_de_veiculos",
    language: "Dart",
    languageList: ["Dart"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "85",
    name: "javascript_pasta",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "86",
    name: "curso-react-native-do-zero-ao-avancado",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "87",
    name: "primeiroApp",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "88",
    name: "nlw04",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "89",
    name: "teste_dart",
    language: "Dart",
    languageList: ["Dart"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "90",
    name: "imersao_react_nextjs_curso",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "91",
    name: "app_flutter_teste",
    language: "Dart",
    languageList: ["Dart"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "92",
    name: "pwa_curso2",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "93",
    name: "pwa_curso",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "94",
    name: "camera_app_api",
    language: "JavaScript ",
    languageList: ["JavaScript "],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "95",
    name: "camera-app",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "96",
    name: "lista_produtos",
    language: "Dart",
    languageList: ["Dart"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "97",
    name: "dp-livewire-dynamic-select",
    language: "PHP",
    languageList: ["PHP"],
    license: "",
    archived: false,
    private: false,
    fork: true,
  },
  {
    id: "98",
    name: "calculadora_app_v1",
    language: "Dart",
    languageList: ["Dart"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "99",
    name: "cursos-laravel-school-of-net",
    language: "PHP",
    languageList: ["PHP"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "100",
    name: "curso-dart-school-of-net",
    language: "Dart",
    languageList: ["Dart"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "101",
    name: "curso-flutter-school-of-net-",
    language: "Dart",
    languageList: ["Dart"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "102",
    name: "react_redux_ts",
    language: "TypeScript ",
    languageList: ["TypeScript "],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "103",
    name: "react_redux_js",
    language: "JavaScript ",
    languageList: ["JavaScript "],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "104",
    name: "site-curriculo-react",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "105",
    name: "site-administravel-php",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "106",
    name: "site-curriculo-react-ts",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "107",
    name: "nlw03",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "108",
    name: "cursos-html-css-school-of-net",
    language: "CSS",
    languageList: ["CSS"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "109",
    name: "curso-javascript-school-of-net",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "110",
    name: "lista-veiculos-ts",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "111",
    name: "site-curriculo-react-ts-2",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "112",
    name: "nlw-02",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "113",
    name: "imersao_react",
    language: "JavaScript ",
    languageList: ["JavaScript "],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "114",
    name: "javascript_teste",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "115",
    name: "nlw-01",
    language: "Typescript",
    languageList: ["Typescript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "116",
    name: "liax-prova-php-07",
    language: "PHP",
    languageList: ["PHP"],
    license: "",
    archived: false,
    private: true,
    fork: true,
  },
  {
    id: "117",
    name: "nlw-01-02",
    language: "TypeScript",
    languageList: ["TypeScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "118",
    name: "javascript-projetos",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "119",
    name: "calcula-medida-mobile",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "120",
    name: "lista-produtos-mobile",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "121",
    name: "lista-produtos-v1",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "122",
    name: "calcula-medida-v1",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "123",
    name: "be-the-hero-2",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: true,
    fork: false,
  },
  {
    id: "124",
    name: "avancando-com-electron",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "125",
    name: "curso-php-exercicios-da-school-of-net",
    language: "PHP",
    languageList: ["PHP"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "126",
    name: "python-projetos",
    language: "Python",
    languageList: ["Python"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "127",
    name: "curso-javascript-alura",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "128",
    name: "Projeto-SuperMercado-Java",
    language: "Java",
    languageList: ["Java"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "129",
    name: "lista-compras-1",
    language: "PHP",
    languageList: ["PHP"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "130",
    name: "curso-php-alura",
    language: "JavaScript",
    languageList: ["JavaScript"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "131",
    name: "RedeSocialColecoesJava",
    language: "Java",
    languageList: ["Java"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "132",
    name: "repositorio-curso-composer-son",
    language: "PHP",
    languageList: ["PHP"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "133",
    name: "curso-python-alura",
    language: "Python",
    languageList: ["Python"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "134",
    name: "DicionarioInglesPortugues",
    language: "Java",
    languageList: ["Java"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "135",
    name: "Caca_niquel_em_java",
    language: "Java",
    languageList: ["Java"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "136",
    name: "ProgramaLoteriaJava",
    language: "Java",
    languageList: ["Java"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "137",
    name: "CalculadoraJava",
    language: "Java",
    languageList: ["Java"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "138",
    name: "git-code-education",
    language: "PHP",
    languageList: ["PHP"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "139",
    name: "curso-android-alura",
    language: "Java",
    languageList: ["Java"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "140",
    name: "Vecx-System-Java-Desktop",
    language: "Java",
    languageList: ["Java"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "142",
    name: "Vecx-system-web",
    language: "PHP",
    languageList: ["PHP"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "143",
    name: "cursos-front-end-alura",
    language: "HTML",
    languageList: ["HTML"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "144",
    name: "curso-less-css-alura",
    language: "CSS",
    languageList: ["CSS"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
  {
    id: "145",
    name: "curso-sass-e-compass-alura",
    language: "CSS",
    languageList: ["CSS"],
    license: "",
    archived: false,
    private: false,
    fork: false,
  },
];










