export const all_user_repositories = [
  {
    "id": 1296269,
    "node_id": "MDEwOlJlcG9zaXRvcnkxMjk2MjY5",
    "name": "Hello-World",
    "full_name": "octocat/Hello-World",
    "owner": {
      "login": "octocat",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/octocat",
      "html_url": "https://github.com/octocat",
      "followers_url": "https://api.github.com/users/octocat/followers",
      "following_url": "https://api.github.com/users/octocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
      "organizations_url": "https://api.github.com/users/octocat/orgs",
      "repos_url": "https://api.github.com/users/octocat/repos",
      "events_url": "https://api.github.com/users/octocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/octocat/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/octocat/Hello-World",
    "description": "This your first repo!",
    "fork": false,
    "url": "https://api.github.com/repos/octocat/Hello-World",
    "archive_url": "https://api.github.com/repos/octocat/Hello-World/{archive_format}{/ref}",
    "assignees_url": "https://api.github.com/repos/octocat/Hello-World/assignees{/user}",
    "blobs_url": "https://api.github.com/repos/octocat/Hello-World/git/blobs{/sha}",
    "branches_url": "https://api.github.com/repos/octocat/Hello-World/branches{/branch}",
    "collaborators_url": "https://api.github.com/repos/octocat/Hello-World/collaborators{/collaborator}",
    "comments_url": "https://api.github.com/repos/octocat/Hello-World/comments{/number}",
    "commits_url": "https://api.github.com/repos/octocat/Hello-World/commits{/sha}",
    "compare_url": "https://api.github.com/repos/octocat/Hello-World/compare/{base}...{head}",
    "contents_url": "https://api.github.com/repos/octocat/Hello-World/contents/{+path}",
    "contributors_url": "https://api.github.com/repos/octocat/Hello-World/contributors",
    "deployments_url": "https://api.github.com/repos/octocat/Hello-World/deployments",
    "downloads_url": "https://api.github.com/repos/octocat/Hello-World/downloads",
    "events_url": "https://api.github.com/repos/octocat/Hello-World/events",
    "forks_url": "https://api.github.com/repos/octocat/Hello-World/forks",
    "git_commits_url": "https://api.github.com/repos/octocat/Hello-World/git/commits{/sha}",
    "git_refs_url": "https://api.github.com/repos/octocat/Hello-World/git/refs{/sha}",
    "git_tags_url": "https://api.github.com/repos/octocat/Hello-World/git/tags{/sha}",
    "git_url": "git:github.com/octocat/Hello-World.git",
    "issue_comment_url": "https://api.github.com/repos/octocat/Hello-World/issues/comments{/number}",
    "issue_events_url": "https://api.github.com/repos/octocat/Hello-World/issues/events{/number}",
    "issues_url": "https://api.github.com/repos/octocat/Hello-World/issues{/number}",
    "keys_url": "https://api.github.com/repos/octocat/Hello-World/keys{/key_id}",
    "labels_url": "https://api.github.com/repos/octocat/Hello-World/labels{/name}",
    "languages_url": "https://api.github.com/repos/octocat/Hello-World/languages",
    "merges_url": "https://api.github.com/repos/octocat/Hello-World/merges",
    "milestones_url": "https://api.github.com/repos/octocat/Hello-World/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/octocat/Hello-World/notifications{?since,all,participating}",
    "pulls_url": "https://api.github.com/repos/octocat/Hello-World/pulls{/number}",
    "releases_url": "https://api.github.com/repos/octocat/Hello-World/releases{/id}",
    "ssh_url": "git@github.com:octocat/Hello-World.git",
    "stargazers_url": "https://api.github.com/repos/octocat/Hello-World/stargazers",
    "statuses_url": "https://api.github.com/repos/octocat/Hello-World/statuses/{sha}",
    "subscribers_url": "https://api.github.com/repos/octocat/Hello-World/subscribers",
    "subscription_url": "https://api.github.com/repos/octocat/Hello-World/subscription",
    "tags_url": "https://api.github.com/repos/octocat/Hello-World/tags",
    "teams_url": "https://api.github.com/repos/octocat/Hello-World/teams",
    "trees_url": "https://api.github.com/repos/octocat/Hello-World/git/trees{/sha}",
    "clone_url": "https://github.com/octocat/Hello-World.git",
    "mirror_url": "git:git.example.com/octocat/Hello-World",
    "hooks_url": "https://api.github.com/repos/octocat/Hello-World/hooks",
    "svn_url": "https://svn.github.com/octocat/Hello-World",
    "homepage": "https://github.com",
    "language": null,
    "forks_count": 9,
    "stargazers_count": 80,
    "watchers_count": 80,
    "size": 108,
    "default_branch": "master",
    "open_issues_count": 0,
    "is_template": false,
    "topics": [
      "octocat",
      "atom",
      "electron",
      "api"
    ],
    "has_issues": true,
    "has_projects": true,
    "has_wiki": true,
    "has_pages": false,
    "has_downloads": true,
    "archived": false,
    "disabled": false,
    "visibility": "public",
    "pushed_at": "2011-01-26T19:06:43Z",
    "created_at": "2011-01-26T19:01:12Z",
    "updated_at": "2011-01-26T19:14:43Z",
    "permissions": {
      "admin": false,
      "push": false,
      "pull": true
    },
    "template_repository": null
  }
]

export const saida2 = [
  {
    allow_forking: true,
    archive_url: "https://api.github.com/repos/otaviohenrique1/aluracord/{archive_format}{/ref}",
    archived: false,
    assignees_url: "https://api.github.com/repos/otaviohenrique1/aluracord/assignees{/user}",
    blobs_url: "https://api.github.com/repos/otaviohenrique1/aluracord/git/blobs{/sha}",
    branches_url: "https://api.github.com/repos/otaviohenrique1/aluracord/branches{/branch}",
    clone_url: "https://github.com/otaviohenrique1/aluracord.git",
    collaborators_url: "https://api.github.com/repos/otaviohenrique1/aluracord/collaborators{/collaborator}",
    comments_url: "https://api.github.com/repos/otaviohenrique1/aluracord/comments{/number}",
    commits_url: "https://api.github.com/repos/otaviohenrique1/aluracord/commits{/sha}",
    compare_url: "https://api.github.com/repos/otaviohenrique1/aluracord/compare/{base}...{head}",
    contents_url: "https://api.github.com/repos/otaviohenrique1/aluracord/contents/{+path}",
    contributors_url: "https://api.github.com/repos/otaviohenrique1/aluracord/contributors",
    created_at: "2022-01-24T23:11:16Z",
    default_branch: "master",
    deployments_url: "https://api.github.com/repos/otaviohenrique1/aluracord/deployments",
    description: null,
    disabled: false,
    downloads_url: "https://api.github.com/repos/otaviohenrique1/aluracord/downloads",
    events_url: "https://api.github.com/repos/otaviohenrique1/aluracord/events",
    fork: false,
    forks: 0,
    forks_count: 0,
    forks_url: "https://api.github.com/repos/otaviohenrique1/aluracord/forks",
    full_name: "otaviohenrique1/aluracord",
    git_commits_url: "https://api.github.com/repos/otaviohenrique1/aluracord/git/commits{/sha}",
    git_refs_url: "https://api.github.com/repos/otaviohenrique1/aluracord/git/refs{/sha}",
    git_tags_url: "https://api.github.com/repos/otaviohenrique1/aluracord/git/tags{/sha}",
    git_url: "git://github.com/otaviohenrique1/aluracord.git",
    has_downloads: true,
    has_issues: true,
    has_pages: false,
    has_projects: true,
    has_wiki: true,
    homepage: null,
    hooks_url: "https://api.github.com/repos/otaviohenrique1/aluracord/hooks",
    html_url: "https://github.com/otaviohenrique1/aluracord",
    id: 451664765,
    is_template: false,
    issue_comment_url: "https://api.github.com/repos/otaviohenrique1/aluracord/issues/comments{/number}",
    issue_events_url: "https://api.github.com/repos/otaviohenrique1/aluracord/issues/events{/number}",
    issues_url: "https://api.github.com/repos/otaviohenrique1/aluracord/issues{/number}",
    keys_url: "https://api.github.com/repos/otaviohenrique1/aluracord/keys{/key_id}",
    labels_url: "https://api.github.com/repos/otaviohenrique1/aluracord/labels{/name}",
    language: "JavaScript",
    languages_url: "https://api.github.com/repos/otaviohenrique1/aluracord/languages",
    license: null,
    merges_url: "https://api.github.com/repos/otaviohenrique1/aluracord/merges",
    milestones_url: "https://api.github.com/repos/otaviohenrique1/aluracord/milestones{/number}",
    mirror_url: null,
    name: "aluracord",
    node_id: "R_kgDOGuvbfQ",
    notifications_url: "https://api.github.com/repos/otaviohenrique1/aluracord/notifications{?since,all,participating}",
    open_issues: 0,
    open_issues_count: 0,
    owner:
    {
      avatar_url: "https://avatars.githubusercontent.com/u/42388160?v=4",
      events_url: "https://api.github.com/users/otaviohenrique1/events{/privacy}",
      followers_url: "https://api.github.com/users/otaviohenrique1/followers",
      following_url: "https://api.github.com/users/otaviohenrique1/following{/other_user}",
      gists_url: "https://api.github.com/users/otaviohenrique1/gists{/gist_id}",
      gravatar_id: "",
      html_url: "https://github.com/otaviohenrique1",
      id: 42388160,
      login: "otaviohenrique1",
      node_id: "MDQ6VXNlcjQyMzg4MTYw",
      organizations_url: "https://api.github.com/users/otaviohenrique1/orgs",
      received_events_url: "https://api.github.com/users/otaviohenrique1/received_events",
      repos_url: "https://api.github.com/users/otaviohenrique1/repos",
      site_admin: false,
      starred_url: "https://api.github.com/users/otaviohenrique1/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/otaviohenrique1/subscriptions",
      type: "User",
      url: "https://api.github.com/users/otaviohenrique1",
    },
    private: false,
    pulls_url: "https://api.github.com/repos/otaviohenrique1/aluracord/pulls{/number}",
    pushed_at: "2022-01-24T23:19:06Z",
    releases_url: "https://api.github.com/repos/otaviohenrique1/aluracord/releases{/id}",
    size: 16,
    ssh_url: "git@github.com:otaviohenrique1/aluracord.git",
    stargazers_count: 0,
    stargazers_url: "https://api.github.com/repos/otaviohenrique1/aluracord/stargazers",
    statuses_url: "https://api.github.com/repos/otaviohenrique1/aluracord/statuses/{sha}",
    subscribers_url: "https://api.github.com/repos/otaviohenrique1/aluracord/subscribers",
    subscription_url: "https://api.github.com/repos/otaviohenrique1/aluracord/subscription",
    svn_url: "https://github.com/otaviohenrique1/aluracord",
    tags_url: "https://api.github.com/repos/otaviohenrique1/aluracord/tags",
    teams_url: "https://api.github.com/repos/otaviohenrique1/aluracord/teams",
    topics: [],
    trees_url: "https://api.github.com/repos/otaviohenrique1/aluracord/git/trees{/sha}",
    updated_at: "2022-07-01T18:29:07Z",
    url: "https://api.github.com/repos/otaviohenrique1/aluracord",
    visibility: "public",
    watchers: 0,
    watchers_count: 0,
    web_commit_signoff_required: false,
  }
];

export const repo_commits = [
  {
    "url": "https://api.github.com/repos/octocat/Hello-World/commits/6dcb09b5b57875f334f61aebed695e2e4193db5e",
    "sha": "6dcb09b5b57875f334f61aebed695e2e4193db5e",
    "node_id": "MDY6Q29tbWl0NmRjYjA5YjViNTc4NzVmMzM0ZjYxYWViZWQ2OTVlMmU0MTkzZGI1ZQ==",
    "html_url": "https://github.com/octocat/Hello-World/commit/6dcb09b5b57875f334f61aebed695e2e4193db5e",
    "comments_url": "https://api.github.com/repos/octocat/Hello-World/commits/6dcb09b5b57875f334f61aebed695e2e4193db5e/comments",
    "commit": {
      "url": "https://api.github.com/repos/octocat/Hello-World/git/commits/6dcb09b5b57875f334f61aebed695e2e4193db5e",
      "author": {
        "name": "Monalisa Octocat",
        "email": "support@github.com",
        "date": "2011-04-14T16:00:49Z"
      },
      "committer": {
        "name": "Monalisa Octocat",
        "email": "support@github.com",
        "date": "2011-04-14T16:00:49Z"
      },
      "message": "Fix all the bugs",
      "tree": {
        "url": "https://api.github.com/repos/octocat/Hello-World/tree/6dcb09b5b57875f334f61aebed695e2e4193db5e",
        "sha": "6dcb09b5b57875f334f61aebed695e2e4193db5e"
      },
      "comment_count": 0,
      "verification": {
        "verified": false,
        "reason": "unsigned",
        "signature": null,
        "payload": null
      }
    },
    "author": {
      "login": "octocat",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/octocat",
      "html_url": "https://github.com/octocat",
      "followers_url": "https://api.github.com/users/octocat/followers",
      "following_url": "https://api.github.com/users/octocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
      "organizations_url": "https://api.github.com/users/octocat/orgs",
      "repos_url": "https://api.github.com/users/octocat/repos",
      "events_url": "https://api.github.com/users/octocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/octocat/received_events",
      "type": "User",
      "site_admin": false
    },
    "committer": {
      "login": "octocat",
      "id": 1,
      "node_id": "MDQ6VXNlcjE=",
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/octocat",
      "html_url": "https://github.com/octocat",
      "followers_url": "https://api.github.com/users/octocat/followers",
      "following_url": "https://api.github.com/users/octocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
      "organizations_url": "https://api.github.com/users/octocat/orgs",
      "repos_url": "https://api.github.com/users/octocat/repos",
      "events_url": "https://api.github.com/users/octocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/octocat/received_events",
      "type": "User",
      "site_admin": false
    },
    "parents": [
      {
        "url": "https://api.github.com/repos/octocat/Hello-World/commits/6dcb09b5b57875f334f61aebed695e2e4193db5e",
        "sha": "6dcb09b5b57875f334f61aebed695e2e4193db5e"
      }
    ]
  }
];